import QRCode from "qrcode";

/**
 * QR code of a share link, rendered on the server as SVG – for readers
 * sitting next to you: point the camera at it, and the app or the browser
 * opens the trip.
 */
export default async function ShareQr({
  url,
  label,
  className,
}: {
  url: string;
  label: string;
  className?: string;
}) {
  const svg = await QRCode.toString(url, {
    type: "svg",
    margin: 1,
    errorCorrectionLevel: "M",
    color: { dark: "#1c1917", light: "#ffffff" },
  });
  return (
    <div
      className={className}
      role="img"
      aria-label={label}
      // Generated by the library from our own URL, not from user input.
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  );
}
